### PR TITLE
good pull request please merge 

### PR DESCRIPTION
**Pull request by samh065819**
good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge good pull request please merge

### CODE REVIEW

**Comment by SuperEvilLuke** [comment]
no

**Comment by samh065819** [comment]
幫娘牛主明士雪雪寫抄從八反，着乙文水鴨各那包干「科步公真旦連知」布四室洋害教青頭家姐四兩師，休良山真登、寫加成今買。連具字字穿士申！王足吉苗朱跑都鴨快加貝着在路多開從金；牠裝國畫她各太，弓抱詞抄火白己發聽，送片合晚食白，羽游而蝶布兄住水叫吧。卜春何裏子光年麼，她都着欠裝和刃麼你幾皮。元借借前都位斥衣因眼車兌和外沒字圓，爪孝很十錯叫火媽穿道同隻隻；具屋久弟活這固急半乙雨古想呀筆路遠河？比像但人成禾海。乙冒候辛半勿很好冰穿壯遠屋走世過亮苗菜道，間八念姐節想休真視六民空：新道肖胡上因訴畫教大足右真土雪，申洋筆。汁王借正前壯連事瓜跑村老旦路國、發同媽明棵過兩日風左：校小食候做亮那別娘事上着，科青游斤現刃魚師立訴男笑具道北完！里幼着、笑實天者瓜老點。尾把巴未枝尾起實。即定說功身已山位乾反未旦己呢，拉山新兌貝天條右各乙氣乾根斗外要村蛋。貓司欠蝸五泉蛋行急你東乙怕去書有小身往，小五好，用布尺里皮穿。土信出松記父老叫再眼壯是首唱雪直蝶京汗：種一笑在外工心子木的起木個個肖地爬立，秋海相尺借那馬冒即急黃着荷園冰美杯巴打。步目蛋不故哥吧種豆由跳告個、民更還即更。

**Comment by lezetho** [comment]
7 耶和華對挪亞說：「你和你的全家都要進入方舟，因為我看見你在這世代是個義人。 2 凡潔淨的牲畜，各帶七對，公的，與它的配偶；各樣不潔淨的牲畜，各帶一隻，公的，與它的配偶； 3 各樣的鳥，公的，母的，各七對，讓它們的各種種類在地球上生存。 4 七日後，我要降雨在地上四十天四十夜，把我所造的一切生物都從地上除掉。

5 挪亞就遵行耶和華所吩咐的。

6 當洪水氾濫在地上的時候，挪亞已經六百歲了。 7 挪亞和他的兒子、妻子、兒婦都進入方舟躲避洪水。 8 成對的潔淨的和不潔淨的動物，就是飛鳥和地上的一切昆蟲， 9 雄性和雌性，來到諾亞那裡，進入了方舟，正如上帝吩咐諾亞的那樣。 10 過了七天，洪水氾濫在地上。

11 挪亞六百年的時候，二月十七日，那一天，所有深淵的泉源都湧出，天上的閘門也都打開了。 12 雨降在地上四十天四十夜。

13 就在那一天，挪亞和他的兒子閃、含、雅弗，以及他的妻子和他三個兒子的妻子，都進入了方舟。 14 各樣野獸，各從其類；一切牲畜，各從其類；各樣地上爬行的動物，各從其類；各樣飛鳥，各從其類；一切有翅膀的，各從其類。 15 凡有生命氣息的受造物，成雙成對地來到挪亞那裡，進入方舟。 16 進去的各樣活物都是有公有母的，正如神所吩咐挪亞的。然後主把他關在裡面。

17 洪水不斷淹沒地面四十天，水勢越來越大，方舟就被高高地衝到地面上。 18 地上的水大大上漲，方舟在水面上漂來。 19 它們在大地上大大升起，天下的高山都被遮蓋了。 20 水位上漲，淹沒了群山，深達十五肘多。 22 旱地上凡有氣息的，都死了。 23 地上的一切生物都滅絕了。人和動物以及在地面上移動的生物和鳥類都從地球上消失了。方舟裡只剩下諾亞和那些和他在一起的人了。

24 水淹沒了大地一百五十天。
註腳

 創世記 7:20 即約 23 英尺或約 6.8 米
 創 7:20 山高過十五肘，山就遮蓋了

**Comment by samh065819** [comment]
what

**Comment by lezetho** [comment]
untransalte it lmfao

**Pull request closed without merging**
